kind: CertificateSigningRequest
apiVersion: certificates.k8s.io/v1
metadata:
   name: prod-user
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FqQ0NBVklDQVFBd0pURVNNQkFHQTFVRUF3d0pjSEp2WkMxMWMyVnlNUTh3RFFZRFZRUUtEQVprWlhadgpjSE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZVdGlLNzlMZ1VKNkI1SHU5CmVYcjNlbEVVUW1KWHVZZnE3Y1NvZUdZdGdMTnV2bUVnY0cwOGtGQUViT2c5OE83M0ZCUm5ybnBURXVaMU9nTUIKK05ISnZkMHJGdStQdHl0SDdLbUlUSzN5SmMraGhKa3hrVG9uWG5tdkN0NEt5bDViMW1ZUDJ3QUVESU13VlJPYgpQdnhPS0ZsdHZlQUxnc2N2aE1uM0VEWFRmVmUvVE1JNUM1VkdUTWNQWFZxckJ2Zi9IamlMQSt3MnR1bmlINGdMCm9vMGoySFZZbEVpTGM5N2xmT2lQN2lOUHhTME5rcitidm9aNFo5K3NhTzIwVUgxVkNOa0pCZFZTbmVQeEkvTHQKUG9seFc2SldCWUFjZXRVQmNybGZRYzFwcUFBRGRZNlJoRE5ndWNuQ0ltL2l2ZVdScm42YUhSaGJGVG1pQzJjcwpnVEVCQWdNQkFBR2dBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRjFldzRyaG5vTWZhc1FuM0pxREY3VlJMCmNQb21Cbkc2bHRlRDE2SzFiUmdaRW5vblg3NDdUdXAxRHRSZFdGS0h2cEFuSkNEcnk4OHh6QnplMlpTZWhEVUUKcXRWS0JDdzhyN2Z1T2pYQnplcEFUbUU3SzdyZ1dXektkUUQrVGM0VW4wWCs2Qm4xZEcwd1pjRTlhZ0pnWDhjSAoycWJzNVNlY1NJaWgzdDVkY1FyTFFnQmZlSTNTOHA2cm9RS0xQRU96cHpZdno2ZUw5MGtWTVhOQXhhek1CQ01rCk00YUh6Q1BySVBCWjBBWnNLUjlDb3ZnaEtOblJBeFNSR3JSS2lmTU85NnpKOVNSZSsyVzF6MzR2T3FMRkxJN3oKYUNmRldxVFBCM3BaSGlQRDNJL3dDUDFlWStPUDcvNkN3YzMyZ3lZeFZaN0NWYk1Sb1pXZ3g1VTMzekppVUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K

  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400
  usages:
  - client auth


# openssl genrsa -out prod-user.key 2048
# openssl req -config csr.conf -new -key prod-user.key -nodes -out prod-user.csr
# cat prod-user.csr | base64 | tr -d '\n'
# kubectl apply -f csr.yml
# kubectl get csr ; kubectl certificate approve prod-user
# kubectl get csr prod-user -o jsonpath="{.status.certificate}" | base64 --decode > prod-user.crt
# modify kubeconfig with 
